// src/types/pet.ts
// TypeScript types for the Pet entity and its API request/response shapes.
//
// Field source of truth:
//   - Pet entity fields   → PetOpsHub-Backend/src/models/pet.model.ts
//   - Create/Update rules → PetOpsHub-Backend/src/schemas/pet.schema.ts (Zod)
//   - API response shape  → PetOpsHub-Backend/src/controllers/pet.controller.ts
//   - List query params   → PetOpsHub-Backend/src/schemas/pet.schema.ts (getPetsQuerySchema)
//
// Conventions match existing frontend types (auth.ts, dashboard.ts):
//   - string timestamps (ISO 8601) — Supabase returns strings over the wire
//   - success: boolean envelope consistent with MeResponse / DashboardSummaryResponse

// ─── Status Enum ─────────────────────────────────────────────────────────────
// Source: pet.schema.ts → petStatusEnum = z.enum(["Active", "Inactive", "Deceased"])
export type PetStatus = 'Active' | 'Inactive' | 'Deceased';

// ─── Pet Entity ───────────────────────────────────────────────────────────────
// Source: src/models/pet.model.ts (all fields, no additions, no omissions)
export interface Pet {
  // ── Core identifiers ──────────────────────────────────────────────────────
  id: string;
  organization_id: string;
  branch_id?: string;
  client_id: string;
  pet_code: string;               // Auto-generated by the backend; read-only on the frontend

  // ── Basic information ──────────────────────────────────────────────────────
  pet_name: string;
  species: string;
  breed?: string;
  gender?: string;
  date_of_birth?: string;         // ISO 8601 string (DB stores timestamptz)
  estimated_birth_date: boolean;
  color?: string;
  weight?: number;
  weight_unit: string;            // Default: "kg"

  // ── Medical identifiers ────────────────────────────────────────────────────
  microchip_number?: string;
  registration_number?: string;
  blood_type?: string;

  // ── Health status ──────────────────────────────────────────────────────────
  sterilized: boolean;
  deceased: boolean;
  deceased_at?: string;           // ISO 8601 string

  // ── Media & notes ─────────────────────────────────────────────────────────
  photo_url?: string;
  notes?: string;
  status: PetStatus;

  // ── Timestamps ────────────────────────────────────────────────────────────
  created_at: string;             // ISO 8601 string
  updated_at: string;             // ISO 8601 string
  deleted_at?: string;            // Soft-delete; ISO 8601 string

  // ── Phase 1 additions: Owner ───────────────────────────────────────────────
  owner_first_name?: string;
  owner_last_name?: string;
  preferred_contact_method?: string;

  // ── Phase 1 additions: Pet activity ───────────────────────────────────────
  pet_service_type?: string;
  pet_last_visit_date?: string;   // ISO 8601 string
  pet_next_visit_date?: string;   // ISO 8601 string

  // ── Phase 1 additions: Membership ─────────────────────────────────────────
  membership_plan?: string;
  membership_status?: string;
  membership_id?: string;
  membership_start_date?: string; // ISO 8601 string
  membership_renewal_date?: string; // ISO 8601 string
  membership_expiry_date?: string;  // ISO 8601 string
  membership_notes?: string;

  // ── Phase 1 additions: Loyalty ────────────────────────────────────────────
  loyalty_points?: string;
  loyalty_tier?: string;
}

// ─── API Response Envelopes ───────────────────────────────────────────────────
// Source: pet.controller.ts response shapes:
//   getPets    → { success: true, data: pets[], total, page, limit }
//   getPetById → { success: true, data: pet }
//   createPet  → { success: true, data: pet }  (201)
//   updatePet  → { success: true, data: pet }
//   deletePet  → { success: true, message: string }

/** Shape returned by GET /api/v1/pets */
export interface PetListResponse {
  success: boolean;
  data: Pet[];
  total: number;
  page: number;
  limit: number;
}

/** Shape returned by GET /api/v1/pets/:id */
export interface PetDetailResponse {
  success: boolean;
  data: Pet;
}

/** Shape returned by POST /api/v1/pets (201) and PUT /api/v1/pets/:id */
export interface PetMutationResponse {
  success: boolean;
  data: Pet;
}

/** Shape returned by DELETE /api/v1/pets/:id */
export interface PetDeleteResponse {
  success: boolean;
  message: string;
}

// ─── Request Payloads ─────────────────────────────────────────────────────────
// Source: createPetSchema body in src/schemas/pet.schema.ts
//   Required: client_id, branch_id, pet_name, species
//   All other fields are optional (schema uses .optional() or .default())
//   Fields NOT accepted on create: id, pet_code, organization_id, created_at,
//     updated_at, deleted_at (all set server-side)

/** POST /api/v1/pets request body */
export interface CreatePetPayload {
  // Required
  client_id: string;
  branch_id: string;
  pet_name: string;
  species: string;

  // Optional core fields
  breed?: string;
  gender?: string;
  date_of_birth?: string;         // ISO 8601 string; coerced to Date by backend
  estimated_birth_date?: boolean; // Default: false
  color?: string;
  weight?: number;
  weight_unit?: string;           // Default: "kg"
  microchip_number?: string;
  registration_number?: string;
  blood_type?: string;
  sterilized?: boolean;           // Default: false
  deceased?: boolean;             // Default: false
  deceased_at?: string;           // ISO 8601 string
  photo_url?: string;             // Must be a valid URL
  notes?: string;
  status?: PetStatus;             // Default: "Active"

  // Optional Phase 1 fields
  owner_first_name?: string;
  owner_last_name?: string;
  preferred_contact_method?: string;
  pet_service_type?: string;
  pet_last_visit_date?: string;   // ISO 8601 string
  pet_next_visit_date?: string;   // ISO 8601 string
  membership_plan?: string;
  membership_status?: string;
  membership_id?: string;
  membership_start_date?: string; // ISO 8601 string
  membership_renewal_date?: string; // ISO 8601 string
  membership_expiry_date?: string;  // ISO 8601 string
  membership_notes?: string;
  loyalty_points?: string;
  loyalty_tier?: string;
}

// Source: updatePetSchema body in src/schemas/pet.schema.ts
//   All fields are optional (partial update).
//   client_id and pet_code are NOT accepted in updates (not in schema).
//   branch_id is optional (validated if present).

/** PUT /api/v1/pets/:id request body */
export interface UpdatePetPayload {
  branch_id?: string;
  pet_name?: string;
  species?: string;
  breed?: string;
  gender?: string;
  date_of_birth?: string;         // ISO 8601 string
  estimated_birth_date?: boolean;
  color?: string;
  weight?: number;
  weight_unit?: string;
  microchip_number?: string;
  registration_number?: string;
  blood_type?: string;
  sterilized?: boolean;
  deceased?: boolean;
  deceased_at?: string;           // ISO 8601 string
  photo_url?: string;             // Must be a valid URL
  notes?: string;
  status?: PetStatus;

  // Phase 1 fields
  owner_first_name?: string;
  owner_last_name?: string;
  preferred_contact_method?: string;
  pet_service_type?: string;
  pet_last_visit_date?: string;   // ISO 8601 string
  pet_next_visit_date?: string;   // ISO 8601 string
  membership_plan?: string;
  membership_status?: string;
  membership_id?: string;
  membership_start_date?: string; // ISO 8601 string
  membership_renewal_date?: string; // ISO 8601 string
  membership_expiry_date?: string;  // ISO 8601 string
  membership_notes?: string;
  loyalty_points?: string;
  loyalty_tier?: string;
}

// ─── Query Parameters ──────────────────────────────────────────────────────────
// Source: getPetsQuerySchema in src/schemas/pet.schema.ts + commonPaginationSchema
//   Supported filters: client_id, branch_id, species, status, search, page, limit

/** Query string parameters accepted by GET /api/v1/pets */
export interface PetListQueryParams {
  page?: number;
  limit?: number;
  client_id?: string;
  branch_id?: string;
  species?: string;
  status?: PetStatus;
  search?: string;                // Searches: pet_name, pet_code, microchip_number
}
